name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
             
      - name: Check Azure CLI
        run: |
         az --version
        continue-on-error: true

      - name: Install Azure CLI
        if: ${{ failure() }}
        run: |
         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
         sudo apt-get install --only-upgrade -y azure-cli

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.7"
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           creds: ${{ secrets.AZURE_CLIENT_SECRET }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Debugging
        run: |
         echo "Azure Subscription ID: $AZURE_SUBSCRIPTION_ID"
         az account show

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
      


      - name: Clean up Terraform files
        run: rm -rf .terraform

      - name: Logout from Azure
        run: az logout
